// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aula13_MTM;

#nullable disable

namespace aula13_MTMPostgreSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241029231324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("HabilidadePessoa", b =>
                {
                    b.Property<int>("HabilidadesHabilidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoasPessoaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HabilidadesHabilidadeId", "PessoasPessoaId");

                    b.HasIndex("PessoasPessoaId");

                    b.ToTable("PessoaHabilidades", (string)null);
                });

            modelBuilder.Entity("aula13_MTM.Habilidade", b =>
                {
                    b.Property<int>("HabilidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HabilidadeId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("aula13_MTM.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("HabilidadePessoa", b =>
                {
                    b.HasOne("aula13_MTM.Habilidade", null)
                        .WithMany()
                        .HasForeignKey("HabilidadesHabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aula13_MTM.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoasPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
